plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.design'
version = '1.0-SNAPSHOT'
description = 'Rate Limiter — Spring Boot REST Controller variant'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':rate-limiter')
    implementation 'org.springframework.boot:spring-boot-starter-web'
}
